#!/usr/bin/env bash

mkdir -p classes &&
cd src/ &&
echo    "/* This file is autogenerated by build.sh */"  > Shaders.java
echo                                                    >> Shaders.java
echo    "public class Shaders {"                        >> Shaders.java
echo    "  private Shaders() { };"                      >> Shaders.java
echo -n "  public static final String VERTEX = \""      >> Shaders.java
cat Minimal.vert | tr -d '\n' >> Shaders.java
echo    "\";"                                           >> Shaders.java
echo -n "  public static final String FRAGMENT = \""    >> Shaders.java
cat Minimal.frag | tr -d '\n' >> Shaders.java
echo    "\";"                                           >> Shaders.java
echo -n "  public static final String PHYSICS = \""     >> Shaders.java
cat Physics.cl | tr -d '\n' >> Shaders.java
echo    "\";"                                           >> Shaders.java
echo    "}"                                             >> Shaders.java
javac -classpath '.:../lib/*' -d ../classes/ Sketch.java